In [1]:
import numpy as np

**Valid Sudoku**

In [4]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [44]:
# getting total/sum of each rows and cdataframe_columns

row_sum = np.sum(s,axis=1)
col_sum = np.sum(s,axis=0)

print(row_sum)
print(col_sum)

[45 45 45 45 45 45 45 45 45]
[45 45 45 45 45 45 45 45 45]


In [45]:
col_sum == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [46]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [48]:
s[0:3,0:3].sum()

np.int64(45)

In [52]:


for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())



    

45
45
45
45
45
45
45
45
45


**General Questions**

In [5]:


# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [43]:
#Get the shape of the matrix.
s.shape

(9, 9)

In [7]:
data.shape

(5, 3)

In [8]:
#Find the average age of students.
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [29]:
age_array = data[0:,0]

In [33]:
age_array

avg_age = age_array.mean()
print(avg_age)

18.4


In [34]:
#Extract Math marks of all students.
math_marks = data[0:,1]
print(math_marks)

[85 92 76 65 90]


In [35]:
#Find the highest Science mark.
science_marks = data[0:,2]
print(science_marks)
max_science_marks = max(science_marks)
print(f"Maximum Science Marks: {max_science_marks}")

[78 88 95 70 85]
Maximum Science Marks: 95


In [53]:
#Get details of the student who scored more than 90 in Math.
math_marks = data[0:,1]


In [56]:
math_marks
print(math_marks)

[85 92 76 65 90]


In [55]:
#Increase Math marks of all students by 5.
print("hello world")

hello world


In [57]:
#Find how many students are younger than 19.
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [61]:
younger_students = data[0:,0] < 19

In [62]:
younger_students


array([ True, False,  True,  True, False])

In [64]:
data[data[0:,0] < 19]

array([[18, 85, 78],
       [17, 76, 95],
       [18, 65, 70]])

In [67]:
#Calculate the average marks in each subject (column-wise mean).
avg_science_marks = data[0:,2].mean()
avg_math_marks = data[0:,1].mean()

print(avg_science_marks)
print(avg_math_marks)

83.2
81.6


In [68]:
#Get data of students who scored at least 80 in both subjects.
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [73]:
(data[data[:,1] >= 80]) & (data[data[:,2] >= 80])

array([[18, 84, 72],
       [17, 76, 88],
       [20, 90, 85]])

In [74]:
#Replace all Science marks < 75 with 0.

data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [75]:
science_marks

array([78, 88, 95, 70, 85])

In [76]:
data[data[:,2] < 75] = 0

In [77]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [ 0,  0,  0],
       [20, 90, 85]])