In [1]:
print("Hello World!")

Hello World!


In [3]:
name = input("Enter Name: ")

print(f"Hello, Nice to Meet you! {name}")

Enter Name:  Arpit


Hello, Nice to Meet you! Arpit


In [4]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# Basic Array Creation

arr = np.array([1,2,3,4,"Hello",7.855])

In [4]:
print(arr)

['1' '2' '3' '4' 'Hello' '7.855']


In [13]:
type(arr)

numpy.ndarray

In [14]:
# Vectors and Matrixes
# Vectors are 1D
# Matrixes are Multi Dimensional

multi_dimensional_array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [15]:
print(multi_dimensional_array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [16]:
# Vectors are 1d
# 2D AND MATRIXES ABOVE 2D ARE TENSORS


In [17]:
# Array Generation Functions

new_array = np.arange(1,11)
print(new_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
# Array of Zeros
zero_arr = np.zeros((6,3))  # rows vs columns
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
# Linspace
arr = np.linspace(1,5,10)  # it proved nmbers b/w a range with equal space.
print(arr)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [31]:
import random
# array of random numbers


In [32]:
np.random.rand(5)

array([0.70326232, 0.0855683 , 0.64818009, 0.09346682, 0.5694203 ])

In [36]:
np.random.randint(6)  # generates a random integer b/w 0 and 6 gives only one

4

In [37]:
np.random.randint(10,20,5) # generates a 5 random integer b/w 10 and 20

array([15, 19, 15, 12, 19], dtype=int32)

In [19]:
# Array Attributes

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr.shape # gives row x cols

(3, 3)

In [22]:
arr.size # size of array


9

In [23]:
arr.dtype  # gives data type of array

dtype('int64')

In [24]:
arr.min()

np.int64(1)

In [25]:
arr.max()

np.int64(9)

In [26]:
arr.sum()

np.int64(45)

In [27]:
# doing sum of array row and column wise
# 0 -> for colums and 1 for row
np.sum(arr,0)

array([12, 15, 18])

In [28]:
np.sum(arr,1)

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.std() # standard deviation

np.float64(2.581988897471611)

In [31]:
arr.argmax()  # gives index of maximum element

np.int64(8)

In [32]:
# reshaping and resizing

In [33]:
arr = np.arange(1,31)
# converting from 1d to 2d matrix
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [34]:
arr = arr.reshape(6,5)

In [35]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
# Indexing and Slicing
# Indexing and Slicing of Vectors
# Indexing and Slicing of Matrixes
# Boolean Slicing

arr = np.arange(11,21)
print(arr)

[11 12 13 14 15 16 17 18 19 20]


In [37]:
print(arr[0])

11


In [38]:
print(arr[-1])

20


In [39]:
print(arr[0:4])

[11 12 13 14]


In [40]:
# Indexing and Slicing of Matrix

arr = np.arange(1,31).reshape(6,5)
print(arr)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [41]:
arr[0][1]

np.int64(2)

In [42]:
arr[2][3]

np.int64(14)

In [45]:
arr[5,4]

# slicing in matrix

arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [14]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [46]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [47]:
# Boolean Indexing
arr = np.arange(11,21)

In [48]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
bool_indx = arr % 2 == 0

In [50]:
bool_indx

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [51]:
arr = arr[bool_indx]
arr

array([12, 14, 16, 18, 20])

In [52]:
# Array Operations

In [53]:
# 1. Airthemetic Operations
# 2. Broadcasting
# 3. Deep and Shallow Coping
# 4. Matrix Operations
# 5. Advance Array Manipulations
# 6. Stacking Array
# 7. Splitting Array

In [54]:
a1 = np.arange(1,6)
a2 = np.arange(6,11)

print(a1)
print(a2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [55]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [56]:
a1-a2

array([-5, -5, -5, -5, -5])

In [57]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [58]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [59]:
# Broadcasting
l = [10,20,30,40]
arr = np.array(l)

In [60]:
arr

array([10, 20, 30, 40])

In [61]:
l+10 # will throw error

TypeError: can only concatenate list (not "int") to list

In [62]:
arr + 10 # can be done in array

array([20, 30, 40, 50])

In [63]:
# deep and shallow coping

In [64]:
a1 = np.arange(1,21)

In [65]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [66]:
slice = a1[0:5]
slice

array([1, 2, 3, 4, 5])

In [67]:
slice * 10

array([10, 20, 30, 40, 50])

In [68]:
a2 = a1

In [69]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [71]:
a2[0] = 100

In [72]:
a1

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [73]:
a2

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [74]:
a3 = a1.copy()
a3[0] = 899

In [75]:
a3

array([899,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [76]:
a1

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [77]:
# Matrix Operations

In [78]:
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(5,9).reshape(2,2)

In [79]:
a1

array([[1, 2],
       [3, 4]])

In [80]:
a2

array([[5, 6],
       [7, 8]])

In [81]:
a1 @ a2 # Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [82]:
np.dot(a1,a2)

array([[19, 22],
       [43, 50]])

In [83]:
# Transpose in Matrix

a1.T

array([[1, 3],
       [2, 4]])

In [84]:
# Array Manipulations and Splittinga1

a1
a2

array([[5, 6],
       [7, 8]])

In [85]:
a1

array([[1, 2],
       [3, 4]])

In [86]:
a2

array([[5, 6],
       [7, 8]])

In [91]:
# Stacking of Array -> It means merging to arrays
# you can not stack arrays only vectorsa1

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [92]:
np.vstack((a,b))  # vertical stack, stack vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [93]:
np.hstack((a,b)) # Horizontally Stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [98]:
# columnstack

np.column_stack((a,b)) # stacking column wise

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [14]:
# splitting using arrays

arr = np.arange(16).reshape(4,4)

In [15]:
np.hsplit(arr,2)  # horizontally split # it works on equal division only

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [17]:
np.vsplit(arr,2)  # Vertically Splitted

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]